- name: Installing gaming related packages and drivers
  ansible.builtin.package:
    state: present
    name:
      # Applications
      - steam
      - lutris
      # Drivers
      - wine-staging
      - giflib
      - lib32-giflib
      - libpng
      - lib32-libpng
      - libldap
      - lib32-libldap
      - gnutls
      - lib32-gnutls
      - mpg123
      - lib32-mpg123
      - openal
      - lib32-openal
      - v4l-utils
      - lib32-v4l-utils
      - libpulse
      - lib32-libpulse
      - libgpg-error
      - lib32-libgpg-error
      - alsa-plugins
      - lib32-alsa-plugins
      - alsa-lib
      - lib32-alsa-lib
      - libjpeg-turbo
      - lib32-libjpeg-turbo
      - sqlite
      - lib32-sqlite
      - libxcomposite
      - lib32-libxcomposite
      - libxinerama
      - lib32-libgcrypt
      - libgcrypt
      - lib32-libxinerama
      - ncurses
      - lib32-ncurses
      - opencl-icd-loader
      - lib32-opencl-icd-loader
      - libxslt
      - lib32-libxslt
      - libva
      - lib32-libva
      - gtk3
      - lib32-gtk3
      - gst-plugins-base-libs
      - lib32-gst-plugins-base-libs
      - vulkan-icd-loader
      - lib32-vulkan-icd-loader
      - mesa
  when: ansible_distribution == "Archlinux"

- name: Download the latest release of Glorious Eggroll Proton
  become: false
  ansible.builtin.uri:
    url: https://api.github.com/repos/GloriousEggroll/proton-ge-custom/releases/latest
    return_content: true
  register: ge_data

- name: Installing the Glorious Eggroll Proton release
  become: false
  vars:
    ge_version: "{{ ge_data.json.tag_name }}"
    proton_directory: "{{ lookup('env', 'HOME') }}/.steam/root/compatibilitytools.d/"
  ansible.builtin.unarchive:
    remote_src: true
    src: "{{ ge_data.json.assets.1.browser_download_url }}"
    dest: "{{ proton_directory }}"
    keep_newer: true
    creates: "{{ proton_directory }}/{{ ge_version }}"
