---
- name: Gathering facts from localhost
  hosts: localhost
  gather_facts: yes
  connection: local
  become: true


  tasks:
    - name: Print OS
      debug: var=ansible_distribution

    - name: Update arch cache
      pacman: update_cache=yes
      changed_when: False
      when: ansible_distribution == "Archlinux"
