---
- hosts: localhost
  connection: local
  become: true
  pre_tasks:
    - name: pre-run | update package cache (arch)
      tags: always
      pacman: update_cache=yes
      changed_when: False
      when: ansible_distribution == "Archlinux"

    - name: pre-run | update package cache (debian, etc)
      tags: always
      apt: update_cache=yes
      changed_when: False
      when: ansible_distribution in ["Debian", "Ubuntu"]

  tasks:
    - name: Installing utility packages
      package:
        state: latest
        name:
          - arandr
          - btop
          - chromium
          - curl
          - deluge
          - flatpak
          - git
          - htop
          - neofetch
          - neovim
          - python-pynvim
          - ranger
          - rsync
          - openssh
          - wget
          - yadm
          - zsh

    - name: Removing unwanted packages
      package:
        state: absent
        name: audacity

    - name: Installing fonts
      package:
        state: latest
        name:
          - noto-fonts
          - ttf-dejavu
          - ttf-fira-code
          - ttf-fira-mono
          - ttf-font-awesome
          - ttf-joypixels
          - ttf-liberation
          - ttf-opensans
          - ttf-ubuntu-font-family
          - adobe-source-han-sans-cn-fonts
          - adobe-source-han-sans-kr-fonts
          - adobe-source-han-sans-jp-fonts
          - otf-fira-mono
          - otf-font-awesome

    - name: Add the flathub flatpak repository remote to the user installation
      flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
        method: user

    - name: Install flatpaks
      flatpak:
        name: 
          - net.cozic.joplin_desktop
          - com.discordapp.Discord
          - com.skype.Client
        state: present

    - name: enable ssh
      service:
        name: sshd
        status: started

- hosts: gamer
  connection: local
  become: true
  tasks:
    - name: Installing gaming related packages and drivers
      package:
        state: latest
        name:
          # Applications
          - steam
          - lutris
          # Drivers
          - wine-staging
          - giflib
          - lib32-giflib
          - libpng
          - lib32-libpng
          - libldap
          - lib32-libldap
          - gnutls
          - lib32-gnutls
          - mpg123
          - lib32-mpg123
          - openal
          - lib32-openal
          - v4l-utils
          - lib32-v4l-utils
          - libpulse
          - lib32-libpulse
          - libgpg-error
          - lib32-libgpg-error
          - alsa-plugins
          - lib32-alsa-plugins
          - alsa-lib
          - lib32-alsa-lib
          - libjpeg-turbo
          - lib32-libjpeg-turbo
          - sqlite
          - lib32-sqlite
          - libxcomposite
          - lib32-libxcomposite
          - libxinerama
          - lib32-libgcrypt
          - libgcrypt
          - lib32-libxinerama
          - ncurses
          - lib32-ncurses
          - opencl-icd-loader
          - lib32-opencl-icd-loader
          - libxslt
          - lib32-libxslt
          - libva
          - lib32-libva
          - gtk3
          - lib32-gtk3
          - gst-plugins-base-libs
          - lib32-gst-plugins-base-libs
          - vulkan-icd-loader
          - lib32-vulkan-icd-loader
          - mesa
      when: ansible_distribution == "Archlinux"


    - name: Install gaming flatpaks
      flatpak:
        name: 
          - net.cozic.joplin_desktop
          - com.discordapp.Discord
          - org.freedesktop.Platform.VulkanLayer.MangoHud
          - com.skype.Client
        state: present

