---
- hosts: all
  become: true
  pre_tasks:
    - name: pre-run | update package cache (arch)
      tags: always
      pacman: 
        update_cache: yes
        upgrade: yes
      changed_when: False
      when: ansible_distribution == "Archlinux"

    - name: pre-run | update package cache (debian, etc)
      tags: always
      apt: 
        update_cache: yes
      changed_when: False 
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: Ensure flatpak is installed
      tags: always
      package:
        state: latest
        name: flatpak

    - name: Ensure flathub is active
      flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

    - name: Ensure RPM Fusion (Free) is active (fedora)
      dnf:
        name: 
          - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm"
          - "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ansible_distribution_major_version}}.noarch.rpm"
        state: present
      when: ansible_distribution == 'Fedora'

  tasks:
    - name: Installing utility packages (Arch)
      package:
        state: latest
        name:
          - arandr
          - btop
          - chromium
          - curl
          - deluge
          - flatpak
          - git
          - htop
          - neofetch
          - neovim
          - python-pynvim
          - ranger
          - rsync
          - openssh
          - wget
          - yadm
          - zsh
      when: ansible_distribution == "Archlinux"

    - name: Installing utility packages (Fedora)
      package:
        state: latest
        name:
          - openssh
          - neovim
          - python3-neovim
          - python3-pip
          - zsh
          - "https://download.opensuse.org/repositories/home:/TheLocehiliosan:/yadm/Fedora_35/noarch/yadm-3.2.1-73.1.noarch.rpm"
      when: ansible_distribution == "Fedora"

    - name: Removing unwanted packages
      package:
        state: absent
        name: audacity

    - name: Installing fonts
      package:
        state: latest
        name:
          - noto-fonts
          - ttf-dejavu
          - ttf-fira-code
          - ttf-fira-mono
          - ttf-font-awesome
          - ttf-joypixels
          - ttf-liberation
          - ttf-opensans
          - ttf-ubuntu-font-family
          - adobe-source-han-sans-cn-fonts
          - adobe-source-han-sans-kr-fonts
          - adobe-source-han-sans-jp-fonts
          - otf-fira-mono
          - otf-font-awesome
      when: ansible_distribution == "Archlinux"



    - name: Install flatpaks
      flatpak:
        name: 
          - net.cozic.joplin_desktop
          - com.discordapp.Discord
          - com.skype.Client
        state: present

    - name: enable ssh
      service:
        name: sshd
        state: started
        enabled: yes

    - name: Clone yadm (fedora)
      git:
        repo: clone https://github.com/TheLocehiliosan/yadm.git 
        dest: ~/.yadm-project
        update: yes
      when: ansible_distribution == "Fedora"


- name: set up zsh for user
  hosts: all
  become: no
  vars:
    the_user: "{{ ansible_user_id }}"
  tasks:
    - name: change user shell to zsh 
      become: yes
      user:
        name: "{{ the_user }}"
        shell: /bin/zsh

