---
- hosts: all
  name: All plays
  become: true
  pre_tasks:
    - name: Pre-run | update package cache (arch)
      tags: always
      community.general.pacman:
        update_cache: true
        upgrade: true
      changed_when: false
      when: ansible_distribution == "Archlinux"

    - name: Pre-run | update package cache (debian, etc)
      tags: always
      ansible.builtin.apt:
        update_cache: true
      changed_when: false
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: Ensure flatpak is installed
      tags: always
      ansible.builtin.package:
        state: present
        name: flatpak

    - name: Ensure Fedora flathub is not in way
      community.general.flatpak_remote:
        name: fedora
        state: absent
      when: ansible_distribution == 'Fedora'

    - name: Ensure flathub is active
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

    - name: Ensure RPM Fusion (Free) is active (fedora)
      ansible.builtin.dnf:
        name:
          - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
          - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
        state: present
        disable_gpg_check: true
      when: ansible_distribution == 'Fedora'

    - name: Removing unwanted packages
      ansible.builtin.package:
        state: absent
        name:
          - audacity
          - jomolhari # Causes issues on Fedora

    - name: Install flatpaks
      community.general.flatpak:
        name:
          - net.cozic.joplin_desktop
          - com.discordapp.Discord
          - com.skype.Client
          - com.microsoft.Teams
        state: present

    - name: Enable ssh
      ansible.builtin.service:
        name: sshd
        state: started
        enabled: true


- name: Tasks that need to be ran as user
  hosts: all
  become: false
  vars:
    user_home: "/home/{{ user }}"
    yadm_location: "{{ user_home }}/.ansible-project"
  tasks:
    - name: Change user shell to zsh
      become: true
      ansible.builtin.user:
        name: "{{ user }}"
        shell: /bin/zsh

    - name: Clone yadm (fedora)
      ansible.builtin.git:
        repo: https://github.com/TheLocehiliosan/yadm.git
        dest: "{{ yadm_location }}"
        clone: true
        version: abf6ea4b610f50f6bf6ff51
      when: ansible_distribution == "Fedora"

    - name: Put yadm in bin
      become: true
      ansible.builtin.file:
        src: "{{ yadm_location }}/yadm"
        dest: /bin/yadm
        state: link
      when: ansible_distribution == "Fedora"

    - name: Install pyenv # noqa: latest
      ansible.builtin.git:
        repo: https://github.com/pyenv/pyenv.git
        dest: ~/.pyenv
        update: false

    - name: Ensure the vim autoload directory exists
      ansible.builtin.file:
        path: "$XDG_DATA_HOME/nvim/site/autoload/"
        mode: 0755
        state: directory

    - name: Ensure private env file exists
      ansible.builtin.file:
        path: "$XDG_CONFIG_HOME/zsh/private_env"
        state: touch
        owner: "{{ user }}"
        mode: 0755
      changed_when: false

    - name: Ensure bwsession file exists
      ansible.builtin.file:
        path: "$XDG_CACHE_HOME/bwsession"
        state: touch
        mode: 0644
      changed_when: false


    - name: Download vim-plug
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: "$XDG_DATA_HOME/nvim/site/autoload/"
        mode: 0644


# run roles
- name: Running base role
  hosts: all
  tags: all
  become: true
  roles:
    - base


- name: Running dev role
  hosts: all
  tags: dev
  become: true
  roles:
    - dev


- name: Running gamer role
  hosts: all
  tags: gamer
  become: true
  roles:
    - gamer
