---
- hosts: all
  become: true
  pre_tasks:
    - name: pre-run | update package cache (arch)
      tags: always
      pacman: update_cache=yes
      changed_when: False
      when: ansible_distribution == "Archlinux"

    - name: pre-run | update package cache (debian, etc)
      tags: always
      apt: update_cache=yes
      changed_when: False
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: Ensure flatpak is installed
      tags: always
      package:
        state: latest
        name: flatpak

    - name: Ensure flathub is active
      flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

  tasks:
    - name: Installing utility packages
      package:
        state: latest
        name:
          - arandr
          - btop
          - chromium
          - curl
          - deluge
          - flatpak
          - git
          - htop
          - neofetch
          - neovim
          - python-pynvim
          - ranger
          - rsync
          - openssh
          - wget
          - yadm
          - zsh

    - name: Removing unwanted packages
      package:
        state: absent
        name: audacity

    - name: Installing fonts
      package:
        state: latest
        name:
          - noto-fonts
          - ttf-dejavu
          - ttf-fira-code
          - ttf-fira-mono
          - ttf-font-awesome
          - ttf-joypixels
          - ttf-liberation
          - ttf-opensans
          - ttf-ubuntu-font-family
          - adobe-source-han-sans-cn-fonts
          - adobe-source-han-sans-kr-fonts
          - adobe-source-han-sans-jp-fonts
          - otf-fira-mono
          - otf-font-awesome



    - name: Install flatpaks
      flatpak:
        name: 
          - net.cozic.joplin_desktop
          - com.discordapp.Discord
          - com.skype.Client
        state: present

    - name: enable ssh
      service:
        name: sshd
        state: started
        enabled: yes

- hosts: gamer
  become: true
  roles:
    - gamer
