- name: Importing distribution specific vars
  ansible.builtin.include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- name: Install essential packages
  ansible.builtin.package:
    state: present
    name: "{{ base_essential_packages }}"
  when: base_essential_packages is defined

- name: Install non-essential packages
  ansible.builtin.package:
    state: present
    name: "{{ base_non_essential_packages }}"
  when: base_non_essential_packages is defined
  tags:
    - skip_ansible_lint
  ignore_errors: true # noqa

- name: Install fonts
  ansible.builtin.package:
    state: present
    name: "{{ base_fonts }}"
  when: fonts is defined

# - name: Enable lightdm
#   ansible.builtin.systemd_service:
#     service: lightdm
#     enabled: true

# Clone Suckless Utils if needed
# - name: Check if DWM already cloned
#   ansible.builtin.stat:
#     path: "$HOME/dwm"
#   register: dwm_path

# - name: Clone dwm build # noqa: latest
#   ansible.builtin.git:
#     repo: https://gitlab.com/michaelagallo95/dwm.git
#     dest: $HOME/dwm
#     clone: true
#     update: false
#     version: HEAD
#   when: not dwm_path.stat.exists

# - name: Check if Dmenu already cloned
#   ansible.builtin.stat:
#     path: "$HOME/dmenu"
#   register: dmenu_path

# - name: Clone dmenu build # noqa: latest
#   ansible.builtin.git:
#     repo: https://gitlab.com/michaelagallo95/dmenu.git
#     dest: $HOME/dmenu
#     clone: true
#     update: false
#     version: HEAD
#   when: not dmenu_path.stat.exists

# - name: Check if st already cloned
#   ansible.builtin.stat:
#     path: "$HOME/st"
#   register: st_path

# - name: Clone st build # noqa: latest
#   ansible.builtin.git:
#     repo: https://github.com/LukeSmithxyz/st.git
#     dest: $HOME/st
#     clone: true
#     update: false
#     version: HEAD
#   when: not st_path.stat.exists

# - name: Create xsession entry for dwm
#   ansible.builtin.copy:
#     dest: /usr/share/xsessions/dwm.desktop
#     content: |
#       [Desktop Entry]
#       Encoding=UTF-8
#       Name=dwm
#       Comment=Dynamic window manager
#       Exec=dwm
#       Icon=dwm
#       Type=XSession
#     mode: "0644"
#     force: false

- name: Run Arch Tasks
  ansible.builtin.include_tasks:
    file: "arch.yml"
  when: ansible_distribution == "Archlinux"
